## Learning numpy from the scratch

In [1]:
import numpy as np

### Creating array from list

In [4]:
arr_1d=np.array([1,2,3,4,5])
print(arr_1d)
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## List vs numpy

In [5]:
py_list=[1,2,3]
print(py_list)

numpy_arr=np.array([1,2,3])
print(numpy_arr)

import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print(f"Time taken for list operation = {time.time()-start}")

start=time.time()
numpy_arr=np.arange(1000000)*2
print(f"Time taken for array operation = {time.time()-start}")

[1, 2, 3]
[1 2 3]
Time taken for list operation = 0.06601095199584961
Time taken for array operation = 0.006922245025634766


### Creating Array from scratch

In [6]:
zeros=np.zeros((3,3))
print(zeros)

ones=np.ones((4,4))
print(ones)

full=np.full((3,3),9)
print(full)

random=np.random.random((3,3))
print(random)

sequence=np.arange(1,12,2)#stop value exclusive
print(sequence)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[0.19431284 0.2973127  0.28274382]
 [0.38687384 0.40489649 0.2319223 ]
 [0.49797234 0.42145569 0.28918238]]
[ 1  3  5  7  9 11]


## Vector Matrix & Tensor

In [7]:
vector=np.array([1,2,3,4,5])
print(f"Vector: {vector}")

matrix=np.array([[1,2,3],[4,5,6]])
print(f"Matrix: {matrix}")

tensor=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(f"Tensor: {tensor}")

Vector: [1 2 3 4 5]
Matrix: [[1 2 3]
 [4 5 6]]
Tensor: [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Array Property

In [9]:
pro_arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Size= {pro_arr.size}")
print(f"Shape= {pro_arr.shape}")
print(f"Dimension= {pro_arr.ndim}")
print(f"Data Type= {pro_arr.dtype}")

Size= 9
Shape= (3, 3)
Dimension= 2
Data Type= int64


## Array Reshaping

In [ ]:
arr=np.arange(12)
reshape=arr.reshape(3,4)
print("Reshapped Array\n")
print(reshape)
print("\n")
flatten=reshape.flatten() #change the original
print("Flatten Array\n")
print(flatten)
print("\n")
ravel=reshape.ravel() # change the view of the origian
print("Ravelled Array\n")
print(ravel)
print("\n")
transpose=reshape.T
print("Transpose Array\n")
print(transpose)
print("\n")

Reshapped Array

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Flatten Array

[ 0  1  2  3  4  5  6  7  8  9 10 11]


Ravelled Array

[ 0  1  2  3  4  5  6  7  8  9 10 11]


Transpose Array

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


